import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";


import NavBarN from "../componet/navbar/NavBarN";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={ `${ geistSans.variable} ${geistMono.variable}   antialiased flex flex-col min-h-screen` }>
        
        <header  >
          <NavBarN />

        </header>
        <main className="flex-1 bg-gray-100  w-full">
       
        {children}

        </main>
        <footer className="bg-gray-300  h-28 flex items-center justify-center">
          <p className="flex text-center items-center  text-sm text-gray-800">
            © {new Date().getFullYear()} zaipher
          </p>
        </footer>
       
      </body>
    </html>
  );
}
